version: '3.8'

services:
    gundo-go-db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
        container_name: gundo-go-db
        networks:
            - api-network
        ports:
            - '3306:3306'
        volumes:
            - ./data_dir:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: gundo-go
            MYSQL_USER: user
            MYSQL_PASSWORD: password

volumes:
    elasticsearch-data:
        driver: local

networks:
    api-network:
        driver: bridge
